### ISSUE TITLE
how to get convert.sh to run in command line?

### ISSUE THREAD

**Issue by carpekd** [wangerzi/3d-model-convert-to-gltf#1]
In your readme, you say download the convert.sh... Where is this, or how do I build this?

**Comment by wangerzi** [comment]
Sorry, I'm developing this function recently, before my docker debugging is complete, you can only use server/convert.py.

**Comment by wangerzi** [comment]
Hi, I'm finished the script mode and build the docker image, you can download the convert.sh and execute this following script, if you need.

```shell
convert.sh [stl|step|iges|obj|fbx] inputpath.stl outputpath.glb # convert to gltf bin file
convert.sh [stl|step|iges|obj|fbx] inputpath.stl outputpath.gltf # not only bin file
```
